[phases.setup]
nixPkgs = [ "nodejs_20" ]

[phases.install]
cmds = [
   "corepack enable",
   "pnpm install"
]

[phases.build]
cmds = [
   "cd apps/web && pnpm build:registry",
   "pnpm --filter=web build"
]

[variables]
NIXPACKS_TURBO_APP_NAME = "web"
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=8192"
NEXT_PUBLIC_APP_URL = "https://your-production-url.com"

[start]
cmd = "cd apps/web && pnpm start"
