[phases.setup]
nixPkgs = [ "nodejs_20" ]

[phases.install]
cmds = [
   "corepack enable",
   "pnpm install"
]

[phases.build]
cmds = [
   "pnpm --filter=nyxb build",
   "pnpm --filter=web build"
]

[variables]
NIXPACKS_TURBO_APP_NAME = "web"
NODE_ENV = "production"
NEXT_PUBLIC_APP_URL = "https://nyxbui.design"

[start]
cmd = "cd apps/web && pnpm start"
