import type { Registry } from '~/registry/schema'

export const examples: Registry = [
   {
      name: 'accordion-demo',
      type: 'components:example',
      registryDependencies: ['accordion'],
      files: ['example/accordion-demo.tsx'],
   },
   {
      name: 'alert-demo',
      type: 'components:example',
      registryDependencies: ['alert'],
      files: ['example/alert-demo.tsx'],
   },
   {
      name: 'alert-destructive',
      type: 'components:example',
      registryDependencies: ['alert'],
      files: ['example/alert-destructive.tsx'],
   },
   {
      name: 'alert-dialog-demo',
      type: 'components:example',
      registryDependencies: ['alert-dialog', 'button'],
      files: ['example/alert-dialog-demo.tsx'],
   },
   {
      name: 'aspect-ratio-demo',
      type: 'components:example',
      registryDependencies: ['aspect-ratio'],
      files: ['example/aspect-ratio-demo.tsx'],
   },
   {
      name: 'avatar-demo',
      type: 'components:example',
      registryDependencies: ['avatar'],
      files: ['example/avatar-demo.tsx'],
   },
   {
      name: 'badge-demo',
      type: 'components:example',
      registryDependencies: ['badge'],
      files: ['example/badge-demo.tsx'],
   },
   {
      name: 'badge-destructive',
      type: 'components:example',
      registryDependencies: ['badge'],
      files: ['example/badge-destructive.tsx'],
   },
   {
      name: 'badge-outline',
      type: 'components:example',
      registryDependencies: ['badge'],
      files: ['example/badge-outline.tsx'],
   },
   {
      name: 'badge-secondary',
      type: 'components:example',
      registryDependencies: ['badge'],
      files: ['example/badge-secondary.tsx'],
   },
   {
      name: 'breadcrumb-demo',
      type: 'components:example',
      registryDependencies: ['breadcrumb'],
      files: ['example/breadcrumb-demo.tsx'],
   },
   {
      name: 'breadcrumb-separator',
      type: 'components:example',
      registryDependencies: ['breadcrumb'],
      files: ['example/breadcrumb-separator.tsx'],
   },
   {
      name: 'breadcrumb-dropdown',
      type: 'components:example',
      registryDependencies: ['breadcrumb'],
      files: ['example/breadcrumb-dropdown.tsx'],
   },
   {
      name: 'breadcrumb-ellipsis',
      type: 'components:example',
      registryDependencies: ['breadcrumb'],
      files: ['example/breadcrumb-ellipsis.tsx'],
   },
   {
      name: 'breadcrumb-link',
      type: 'components:example',
      registryDependencies: ['breadcrumb'],
      files: ['example/breadcrumb-link.tsx'],
   },
   {
      name: 'breadcrumb-responsive',
      type: 'components:example',
      registryDependencies: ['breadcrumb'],
      files: ['example/breadcrumb-responsive.tsx'],
   },
   {
      name: 'button-demo',
      type: 'components:example',
      registryDependencies: ['button'],
      files: ['example/button-demo.tsx'],
   },
   {
      name: 'button-secondary',
      type: 'components:example',
      registryDependencies: ['button'],
      files: ['example/button-secondary.tsx'],
   },
   {
      name: 'button-destructive',
      type: 'components:example',
      registryDependencies: ['button'],
      files: ['example/button-destructive.tsx'],
   },
   {
      name: 'button-outline',
      type: 'components:example',
      registryDependencies: ['button'],
      files: ['example/button-outline.tsx'],
   },
   {
      name: 'button-ghost',
      type: 'components:example',
      registryDependencies: ['button'],
      files: ['example/button-ghost.tsx'],
   },
   {
      name: 'button-link',
      type: 'components:example',
      registryDependencies: ['button'],
      files: ['example/button-link.tsx'],
   },
   {
      name: 'button-with-icon',
      type: 'components:example',
      registryDependencies: ['button'],
      files: ['example/button-with-icon.tsx'],
   },
   {
      name: 'button-loading',
      type: 'components:example',
      registryDependencies: ['button'],
      files: ['example/button-loading.tsx'],
   },
   {
      name: 'button-icon',
      type: 'components:example',
      registryDependencies: ['button'],
      files: ['example/button-icon.tsx'],
   },
   {
      name: 'button-as-child',
      type: 'components:example',
      registryDependencies: ['button'],
      files: ['example/button-as-child.tsx'],
   },
   {
      name: 'pulsating-button-demo',
      type: 'components:example',
      files: ['example/pulsating-button-demo.tsx'],
   },
   {
      name: 'calendar-demo',
      type: 'components:example',
      registryDependencies: ['calendar'],
      files: ['example/calendar-demo.tsx'],
   },
   {
      name: 'calendar-form',
      type: 'components:example',
      registryDependencies: ['calendar', 'form', 'popover'],
      files: ['example/calendar-form.tsx'],
   },
   {
      name: 'card-demo',
      type: 'components:example',
      registryDependencies: ['card', 'button', 'switch'],
      files: ['example/card-demo.tsx'],
   },
   {
      name: 'card-with-form',
      type: 'components:example',
      registryDependencies: ['button', 'card', 'input', 'label', 'select'],
      files: ['example/card-with-form.tsx'],
   },
   {
      name: 'carousel-demo',
      type: 'components:example',
      registryDependencies: ['carousel'],
      files: ['example/carousel-demo.tsx'],
   },
   {
      name: 'carousel-size',
      type: 'components:example',
      registryDependencies: ['carousel'],
      files: ['example/carousel-size.tsx'],
   },
   {
      name: 'carousel-spacing',
      type: 'components:example',
      registryDependencies: ['carousel'],
      files: ['example/carousel-spacing.tsx'],
   },
   {
      name: 'carousel-orientation',
      type: 'components:example',
      registryDependencies: ['carousel'],
      files: ['example/carousel-orientation.tsx'],
   },
   {
      name: 'carousel-dots',
      type: 'components:example',
      registryDependencies: ['carousel'],
      files: ['example/carousel-dots.tsx'],
   },
   {
      name: 'carousel-api',
      type: 'components:example',
      registryDependencies: ['carousel'],
      files: ['example/carousel-api.tsx'],
   },
   {
      name: 'carousel-plugin',
      type: 'components:example',
      registryDependencies: ['carousel'],
      files: ['example/carousel-plugin.tsx'],
   },
   {
      name: 'checkbox-demo',
      type: 'components:example',
      registryDependencies: ['checkbox'],
      files: ['example/checkbox-demo.tsx'],
   },
   {
      name: 'checkbox-disabled',
      type: 'components:example',
      registryDependencies: ['checkbox'],
      files: ['example/checkbox-disabled.tsx'],
   },
   {
      name: 'checkbox-form-multiple',
      type: 'components:example',
      registryDependencies: ['checkbox', 'form'],
      files: ['example/checkbox-form-multiple.tsx'],
   },
   {
      name: 'checkbox-form-single',
      type: 'components:example',
      registryDependencies: ['checkbox', 'form'],
      files: ['example/checkbox-form-single.tsx'],
   },
   {
      name: 'checkbox-with-text',
      type: 'components:example',
      registryDependencies: ['checkbox'],
      files: ['example/checkbox-with-text.tsx'],
   },
   {
      name: 'collapsible-demo',
      type: 'components:example',
      registryDependencies: ['collapsible'],
      files: ['example/collapsible-demo.tsx'],
   },
   {
      name: 'combobox-demo',
      type: 'components:example',
      registryDependencies: ['command'],
      files: ['example/combobox-demo.tsx'],
   },
   {
      name: 'combobox-dropdown-menu',
      type: 'components:example',
      registryDependencies: ['command', 'dropdown-menu', 'button'],
      files: ['example/combobox-dropdown-menu.tsx'],
   },
   {
      name: 'combobox-form',
      type: 'components:example',
      registryDependencies: ['command', 'form'],
      files: ['example/combobox-form.tsx'],
   },
   {
      name: 'combobox-popover',
      type: 'components:example',
      registryDependencies: ['combobox', 'popover'],
      files: ['example/combobox-popover.tsx'],
   },
   {
      name: 'combobox-responsive',
      type: 'components:example',
      registryDependencies: ['combobox', 'popover', 'drawer'],
      files: ['example/combobox-responsive.tsx'],
   },
   {
      name: 'command-demo',
      type: 'components:example',
      registryDependencies: ['command'],
      files: ['example/command-demo.tsx'],
   },
   {
      name: 'command-dialog',
      type: 'components:example',
      registryDependencies: ['command', 'dialog'],
      files: ['example/command-dialog.tsx'],
   },
   {
      name: 'context-menu-demo',
      type: 'components:example',
      registryDependencies: ['context-menu'],
      files: ['example/context-menu-demo.tsx'],
   },
   {
      name: 'data-table-demo',
      type: 'components:example',
      registryDependencies: ['data-table'],
      files: ['example/data-table-demo.tsx'],
   },
   {
      name: 'date-picker-demo',
      type: 'components:example',
      registryDependencies: ['button', 'calendar', 'popover'],
      files: ['example/date-picker-demo.tsx'],
      dependencies: ['date-fns'],
   },
   {
      name: 'date-picker-form',
      type: 'components:example',
      registryDependencies: ['button', 'calendar', 'form', 'popover'],
      files: ['example/date-picker-form.tsx'],
      dependencies: ['date-fns'],
   },
   {
      name: 'date-picker-with-presets',
      type: 'components:example',
      registryDependencies: ['button', 'calendar', 'popover', 'select'],
      files: ['example/date-picker-with-presets.tsx'],
      dependencies: ['date-fns'],
   },
   {
      name: 'date-picker-with-range',
      type: 'components:example',
      registryDependencies: ['button', 'calendar', 'popover'],
      files: ['example/date-picker-with-range.tsx'],
      dependencies: ['date-fns'],
   },
   {
      name: 'dialog-demo',
      type: 'components:example',
      registryDependencies: ['dialog'],
      files: ['example/dialog-demo.tsx'],
   },
   {
      name: 'dialog-close-button',
      type: 'components:example',
      registryDependencies: ['dialog', 'button'],
      files: ['example/dialog-close-button.tsx'],
   },
   {
      name: 'drawer-demo',
      type: 'components:example',
      registryDependencies: ['drawer'],
      files: ['example/drawer-demo.tsx'],
   },
   {
      name: 'drawer-dialog',
      type: 'components:example',
      registryDependencies: ['drawer', 'dialog'],
      files: ['example/drawer-dialog.tsx'],
   },
   {
      name: 'dropdown-menu-demo',
      type: 'components:example',
      registryDependencies: ['dropdown-menu'],
      files: ['example/dropdown-menu-demo.tsx'],
   },
   {
      name: 'dropdown-menu-checkboxes',
      type: 'components:example',
      registryDependencies: ['dropdown-menu', 'checkbox'],
      files: ['example/dropdown-menu-checkboxes.tsx'],
   },
   {
      name: 'dropdown-menu-radio-group',
      type: 'components:example',
      registryDependencies: ['dropdown-menu', 'radio-group'],
      files: ['example/dropdown-menu-radio-group.tsx'],
   },
   {
      name: 'hover-card-demo',
      type: 'components:example',
      registryDependencies: ['hover-card'],
      files: ['example/hover-card-demo.tsx'],
   },
   {
      name: 'input-demo',
      type: 'components:example',
      registryDependencies: ['input'],
      files: ['example/input-demo.tsx'],
   },
   {
      name: 'input-disabled',
      type: 'components:example',
      registryDependencies: ['input'],
      files: ['example/input-disabled.tsx'],
   },
   {
      name: 'input-file',
      type: 'components:example',
      registryDependencies: ['input'],
      files: ['example/input-file.tsx'],
   },
   {
      name: 'input-form',
      type: 'components:example',
      registryDependencies: ['input', 'button', 'form'],
      files: ['example/input-form.tsx'],
   },
   {
      name: 'input-with-button',
      type: 'components:example',
      registryDependencies: ['input', 'button'],
      files: ['example/input-with-button.tsx'],
   },
   {
      name: 'input-with-label',
      type: 'components:example',
      registryDependencies: ['input', 'button', 'label'],
      files: ['example/input-with-label.tsx'],
   },
   {
      name: 'input-with-text',
      type: 'components:example',
      registryDependencies: ['input', 'button', 'label'],
      files: ['example/input-with-text.tsx'],
   },
   {
      name: 'input-otp-demo',
      type: 'components:example',
      registryDependencies: ['input-otp'],
      files: ['example/input-otp-demo.tsx'],
   },
   {
      name: 'input-otp-pattern',
      type: 'components:example',
      registryDependencies: ['input-otp'],
      files: ['example/input-otp-pattern.tsx'],
   },
   {
      name: 'input-otp-separator',
      type: 'components:example',
      registryDependencies: ['input-otp'],
      files: ['example/input-otp-separator.tsx'],
   },
   {
      name: 'input-otp-controlled',
      type: 'components:example',
      registryDependencies: ['input-otp'],
      files: ['example/input-otp-controlled.tsx'],
   },
   {
      name: 'input-otp-form',
      type: 'components:example',
      registryDependencies: ['input-otp', 'form'],
      files: ['example/input-otp-form.tsx'],
   },
   {
      name: 'input-otp-disabled',
      type: 'components:example',
      registryDependencies: ['input-otp', 'form'],
      files: ['example/input-otp-disabled.tsx'],
   },
   {
      name: 'input-phone-default',
      type: 'components:example',
      registryDependencies: ['button', 'input', 'popover'],
      files: ['example/input-phone-default.tsx'],
   },
   {
      name: 'input-phone-demo',
      type: 'components:example',
      registryDependencies: ['button', 'input', 'popover'],
      files: ['example/input-phone-demo.tsx'],
   },
   {
      name: 'input-phone-form',
      type: 'components:example',
      registryDependencies: ['button', 'input', 'popover'],
      files: ['example/input-phone-form.tsx'],
   },
   {
      name: 'input-phone-initial',
      type: 'components:example',
      registryDependencies: ['button', 'input', 'popover'],
      files: ['example/input-phone-initial.tsx'],
   },
   {
      name: 'input-phone-international',
      type: 'components:example',
      registryDependencies: ['button', 'input', 'popover'],
      files: ['example/input-phone-international.tsx'],
   },
   {
      name: 'input-phone-national',
      type: 'components:example',
      registryDependencies: ['button', 'input', 'popover'],
      files: ['example/input-phone-national.tsx'],
   },
   {
      name: 'label-demo',
      type: 'components:example',
      registryDependencies: ['label'],
      files: ['example/label-demo.tsx'],
   },
   {
      name: 'menubar-demo',
      type: 'components:example',
      registryDependencies: ['menubar'],
      files: ['example/menubar-demo.tsx'],
   },
   {
      name: 'navigation-menu-demo',
      type: 'components:example',
      registryDependencies: ['navigation-menu'],
      files: ['example/navigation-menu-demo.tsx'],
   },
   {
      name: 'pagination-demo',
      type: 'components:example',
      registryDependencies: ['pagination'],
      files: ['example/pagination-demo.tsx'],
   },
   {
      name: 'popover-demo',
      type: 'components:example',
      registryDependencies: ['popover'],
      files: ['example/popover-demo.tsx'],
   },
   {
      name: 'progress-demo',
      type: 'components:example',
      registryDependencies: ['progress'],
      files: ['example/progress-demo.tsx'],
   },
   {
      name: 'radio-group-demo',
      type: 'components:example',
      registryDependencies: ['radio-group'],
      files: ['example/radio-group-demo.tsx'],
   },
   {
      name: 'radio-group-form',
      type: 'components:example',
      registryDependencies: ['radio-group', 'form'],
      files: ['example/radio-group-form.tsx'],
   },
   {
      name: 'resizable-demo',
      type: 'components:example',
      registryDependencies: ['resizable'],
      files: ['example/resizable-demo.tsx'],
   },
   {
      name: 'resizable-demo-with-handle',
      type: 'components:example',
      registryDependencies: ['resizable'],
      files: ['example/resizable-demo-with-handle.tsx'],
   },
   {
      name: 'resizable-vertical',
      type: 'components:example',
      registryDependencies: ['resizable'],
      files: ['example/resizable-vertical.tsx'],
   },
   {
      name: 'resizable-handle',
      type: 'components:example',
      registryDependencies: ['resizable'],
      files: ['example/resizable-handle.tsx'],
   },
   {
      name: 'scroll-area-demo',
      type: 'components:example',
      registryDependencies: ['scroll-area'],
      files: ['example/scroll-area-demo.tsx'],
   },
   {
      name: 'scroll-area-horizontal-demo',
      type: 'components:example',
      registryDependencies: ['scroll-area'],
      files: ['example/scroll-area-horizontal-demo.tsx'],
   },
   {
      name: 'select-demo',
      type: 'components:example',
      registryDependencies: ['select'],
      files: ['example/select-demo.tsx'],
   },
   {
      name: 'select-scrollable',
      type: 'components:example',
      registryDependencies: ['select'],
      files: ['example/select-scrollable.tsx'],
   },
   {
      name: 'select-form',
      type: 'components:example',
      registryDependencies: ['select'],
      files: ['example/select-form.tsx'],
   },
   {
      name: 'separator-demo',
      type: 'components:example',
      registryDependencies: ['separator'],
      files: ['example/separator-demo.tsx'],
   },
   {
      name: 'sheet-demo',
      type: 'components:example',
      registryDependencies: ['sheet'],
      files: ['example/sheet-demo.tsx'],
   },
   {
      name: 'sheet-side',
      type: 'components:example',
      registryDependencies: ['sheet'],
      files: ['example/sheet-side.tsx'],
   },
   {
      name: 'skeleton-demo',
      type: 'components:example',
      registryDependencies: ['skeleton'],
      files: ['example/skeleton-demo.tsx'],
   },
   {
      name: 'skeleton-card',
      type: 'components:example',
      registryDependencies: ['skeleton'],
      files: ['example/skeleton-card.tsx'],
   },
   {
      name: 'slider-demo',
      type: 'components:example',
      registryDependencies: ['slider'],
      files: ['example/slider-demo.tsx'],
   },
   {
      name: 'slider-disabled',
      type: 'components:example',
      registryDependencies: ['slider'],
      files: ['example/slider-disabled.tsx'],
   },
   {
      name: 'slider-inverted',
      type: 'components:example',
      registryDependencies: ['slider'],
      files: ['example/slider-inverted.tsx'],
   },
   {
      name: 'slider-vertical',
      type: 'components:example',
      registryDependencies: ['slider'],
      files: ['example/slider-vertical.tsx'],
   },
   {
      name: 'slider-range',
      type: 'components:example',
      registryDependencies: ['slider'],
      files: ['example/slider-range.tsx'],
   },
   {
      name: 'slider-tick-marks-half',
      type: 'components:example',
      registryDependencies: ['slider'],
      files: ['example/slider-tick-marks-half.tsx'],
   },
   {
      name: 'slider-tick-marks-full',
      type: 'components:example',
      registryDependencies: ['slider'],
      files: ['example/slider-tick-marks-full.tsx'],
   },
   {
      name: 'slider-format-label',
      type: 'components:example',
      registryDependencies: ['slider'],
      files: ['example/slider-format-label.tsx'],
   },
   {
      name: 'slider-format-label-side',
      type: 'components:example',
      registryDependencies: ['slider'],
      files: ['example/slider-format-label-side.tsx'],
   },
   {
      name: 'sonner-demo',
      type: 'components:example',
      registryDependencies: ['sonner'],
      files: ['example/sonner-demo.tsx'],
   },
   {
      name: 'switch-demo',
      type: 'components:example',
      registryDependencies: ['switch'],
      files: ['example/switch-demo.tsx'],
   },
   {
      name: 'switch-form',
      type: 'components:example',
      registryDependencies: ['switch', 'form'],
      files: ['example/switch-form.tsx'],
   },
   {
      name: 'table-demo',
      type: 'components:example',
      registryDependencies: ['table'],
      files: ['example/table-demo.tsx'],
   },
   {
      name: 'tabs-demo',
      type: 'components:example',
      registryDependencies: ['tabs'],
      files: ['example/tabs-demo.tsx'],
   },
   {
      name: 'textarea-demo',
      type: 'components:example',
      registryDependencies: ['textarea'],
      files: ['example/textarea-demo.tsx'],
   },
   {
      name: 'textarea-disabled',
      type: 'components:example',
      registryDependencies: ['textarea'],
      files: ['example/textarea-disabled.tsx'],
   },
   {
      name: 'textarea-form',
      type: 'components:example',
      registryDependencies: ['textarea', 'form'],
      files: ['example/textarea-form.tsx'],
   },
   {
      name: 'textarea-with-button',
      type: 'components:example',
      registryDependencies: ['textarea', 'button'],
      files: ['example/textarea-with-button.tsx'],
   },
   {
      name: 'textarea-with-label',
      type: 'components:example',
      registryDependencies: ['textarea', 'label'],
      files: ['example/textarea-with-label.tsx'],
   },
   {
      name: 'textarea-with-text',
      type: 'components:example',
      registryDependencies: ['textarea', 'label'],
      files: ['example/textarea-with-text.tsx'],
   },
   {
      name: 'toast-demo',
      type: 'components:example',
      registryDependencies: ['toast'],
      files: ['example/toast-demo.tsx'],
   },
   {
      name: 'toast-destructive',
      type: 'components:example',
      registryDependencies: ['toast'],
      files: ['example/toast-destructive.tsx'],
   },
   {
      name: 'toast-simple',
      type: 'components:example',
      registryDependencies: ['toast'],
      files: ['example/toast-simple.tsx'],
   },
   {
      name: 'toast-with-action',
      type: 'components:example',
      registryDependencies: ['toast'],
      files: ['example/toast-with-action.tsx'],
   },
   {
      name: 'toast-with-title',
      type: 'components:example',
      registryDependencies: ['toast'],
      files: ['example/toast-with-title.tsx'],
   },
   {
      name: 'toggle-group-demo',
      type: 'components:example',
      registryDependencies: ['toggle-group'],
      files: ['example/toggle-group-demo.tsx'],
   },
   {
      name: 'toggle-group-disabled',
      type: 'components:example',
      registryDependencies: ['toggle-group'],
      files: ['example/toggle-group-disabled.tsx'],
   },
   {
      name: 'toggle-group-lg',
      type: 'components:example',
      registryDependencies: ['toggle-group'],
      files: ['example/toggle-group-lg.tsx'],
   },
   {
      name: 'toggle-group-outline',
      type: 'components:example',
      registryDependencies: ['toggle-group'],
      files: ['example/toggle-group-outline.tsx'],
   },
   {
      name: 'toggle-group-sm',
      type: 'components:example',
      registryDependencies: ['toggle-group'],
      files: ['example/toggle-group-sm.tsx'],
   },
   {
      name: 'toggle-group-single',
      type: 'components:example',
      registryDependencies: ['toggle-group'],
      files: ['example/toggle-group-single.tsx'],
   },
   {
      name: 'toggle-demo',
      type: 'components:example',
      registryDependencies: ['toggle'],
      files: ['example/toggle-demo.tsx'],
   },
   {
      name: 'toggle-disabled',
      type: 'components:example',
      registryDependencies: ['toggle'],
      files: ['example/toggle-disabled.tsx'],
   },
   {
      name: 'toggle-lg',
      type: 'components:example',
      registryDependencies: ['toggle'],
      files: ['example/toggle-lg.tsx'],
   },
   {
      name: 'toggle-outline',
      type: 'components:example',
      registryDependencies: ['toggle'],
      files: ['example/toggle-outline.tsx'],
   },
   {
      name: 'toggle-sm',
      type: 'components:example',
      registryDependencies: ['toggle'],
      files: ['example/toggle-sm.tsx'],
   },
   {
      name: 'toggle-with-text',
      type: 'components:example',
      registryDependencies: ['toggle'],
      files: ['example/toggle-with-text.tsx'],
   },
   {
      name: 'mode-toggle-group',
      type: 'components:example',
      files: ['example/mode-toggle-group.tsx'],
   },
   {
      name: 'tooltip-demo',
      type: 'components:example',
      registryDependencies: ['tooltip'],
      files: ['example/tooltip-demo.tsx'],
   },
   {
      name: 'tooltip-outline',
      type: 'components:example',
      registryDependencies: ['tooltip'],
      files: ['example/tooltip-outline.tsx'],
   },
   {
      name: 'tooltip-secondary',
      type: 'components:example',
      registryDependencies: ['tooltip'],
      files: ['example/tooltip-secondary.tsx'],
   },
   {
      name: 'tooltip-with-toggle-demo',
      type: 'components:example',
      registryDependencies: ['tooltip'],
      files: ['example/tooltip-with-toggle-demo.tsx'],
   },
   {
      name: 'typography-blockquote',
      type: 'components:example',
      files: ['example/typography-blockquote.tsx'],
   },
   {
      name: 'typography-demo',
      type: 'components:example',
      files: ['example/typography-demo.tsx'],
   },
   {
      name: 'typography-h1',
      type: 'components:example',
      files: ['example/typography-h1.tsx'],
   },
   {
      name: 'typography-h2',
      type: 'components:example',
      files: ['example/typography-h2.tsx'],
   },
   {
      name: 'typography-h3',
      type: 'components:example',
      files: ['example/typography-h3.tsx'],
   },
   {
      name: 'typography-h4',
      type: 'components:example',
      files: ['example/typography-h4.tsx'],
   },
   {
      name: 'typography-inline-code',
      type: 'components:example',
      files: ['example/typography-inline-code.tsx'],
   },
   {
      name: 'typography-large',
      type: 'components:example',
      files: ['example/typography-large.tsx'],
   },
   {
      name: 'typography-lead',
      type: 'components:example',
      files: ['example/typography-lead.tsx'],
   },
   {
      name: 'typography-list',
      type: 'components:example',
      files: ['example/typography-list.tsx'],
   },
   {
      name: 'typography-muted',
      type: 'components:example',
      files: ['example/typography-muted.tsx'],
   },
   {
      name: 'typography-p',
      type: 'components:example',
      files: ['example/typography-p.tsx'],
   },
   {
      name: 'typography-small',
      type: 'components:example',
      files: ['example/typography-small.tsx'],
   },
   {
      name: 'typography-table',
      type: 'components:example',
      files: ['example/typography-table.tsx'],
   },
   {
      name: 'mode-toggle',
      type: 'components:example',
      files: ['example/mode-toggle.tsx'],
   },
   {
      name: 'cards',
      type: 'components:example',
      files: ['example/cards/cards.tsx'],
   },
   {
      name: 'chart-bar-demo',
      type: 'components:example',
      files: ['example/chart-bar-demo.tsx'],
   },
   {
      name: 'chart-bar-demo-grid',
      type: 'components:example',
      files: ['example/chart-bar-demo-grid.tsx'],
   },
   {
      name: 'chart-bar-demo-axis',
      type: 'components:example',
      files: ['example/chart-bar-demo-axis.tsx'],
   },
   {
      name: 'chart-bar-demo-tooltip',
      type: 'components:example',
      files: ['example/chart-bar-demo-tooltip.tsx'],
   },
   {
      name: 'chart-bar-demo-legend',
      type: 'components:example',
      files: ['example/chart-bar-demo-legend.tsx'],
   },
   {
      name: 'chart-tooltip-demo',
      type: 'components:example',
      files: ['example/chart-tooltip-demo.tsx'],
   },
   {
      name: 'magic-card-demo',
      type: 'components:example',
      files: ['example/magic-card-demo.tsx'],
   },
   {
      name: 'neon-gradient-card-demo',
      type: 'components:example',
      files: ['example/neon-gradient-card-demo.tsx'],
   },
   {
      name: 'magic-card-gradient',
      type: 'components:example',
      files: ['example/magic-card-gradient.tsx'],
   },
   {
      name: 'linear-gradient-demo',
      type: 'components:example',
      files: ['example/linear-gradient-demo.tsx'],
   },
   {
      name: 'radial-gradient-demo',
      type: 'components:example',
      files: ['example/radial-gradient-demo.tsx'],
   },
   {
      name: 'meteors-demo',
      type: 'components:example',
      files: ['example/meteors-demo.tsx'],
   },
   {
      name: 'grid-pattern-demo',
      type: 'components:example',
      files: ['example/grid-pattern-demo.tsx'],
   },
   {
      name: 'grid-pattern-linear-gradient',
      type: 'components:example',
      files: ['example/grid-pattern-linear-gradient.tsx'],
   },
   {
      name: 'grid-pattern-dashed',
      type: 'components:example',
      files: ['example/grid-pattern-dashed.tsx'],
   },
   {
      name: 'dot-pattern-demo',
      type: 'components:example',
      files: ['example/dot-pattern-demo.tsx'],
   },
   {
      name: 'dot-pattern-linear-gradient',
      type: 'components:example',
      files: ['example/dot-pattern-linear-gradient.tsx'],
   },
   {
      name: 'marquee-demo',
      type: 'components:example',
      files: ['example/marquee-demo.tsx'],
   },
   {
      name: 'marquee-demo-vertical',
      type: 'components:example',
      files: ['example/marquee-demo-vertical.tsx'],
   },
   {
      name: 'marquee-logos',
      type: 'components:example',
      files: ['example/marquee-logos.tsx'],
   },
   {
      name: 'marquee-3d',
      type: 'components:example',
      files: ['example/marquee-3d.tsx'],
   },
   {
      name: 'globe-demo',
      type: 'components:example',
      files: ['example/globe-demo.tsx'],
   },
   {
      name: 'tweet-card-demo',
      type: 'components:example',
      files: ['example/tweet-card-demo.tsx'],
   },
   {
      name: 'tweet-card-images',
      type: 'components:example',
      files: ['example/tweet-card-images.tsx'],
   },
   {
      name: 'tweet-card-meta-preview',
      type: 'components:example',
      files: ['example/tweet-card-meta-preview.tsx'],
   },
   {
      name: 'shimmer-button-demo',
      type: 'components:example',
      files: ['example/shimmer-button-demo.tsx'],
   },
   {
      name: 'hero-video-demo',
      type: 'components:example',
      files: ['example/hero-video-demo.tsx'],
   },
   {
      name: 'hero-video-youtube',
      type: 'components:example',
      files: ['example/hero-video-youtube.tsx'],
   },
   {
      name: 'bento-demo',
      type: 'components:example',
      files: ['example/bento-demo.tsx'],
   },
   {
      name: 'bento-demo-vertical',
      type: 'components:example',
      files: ['example/bento-demo-vertical.tsx'],
   },
   {
      name: 'number-ticker-demo',
      type: 'components:example',
      files: ['example/number-ticker-demo.tsx'],
   },
   {
      name: 'ripple-demo',
      type: 'components:example',
      files: ['example/ripple-demo.tsx'],
   },
   {
      name: 'retro-grid-demo',
      type: 'components:example',
      files: ['example/retro-grid-demo.tsx'],
   },
   {
      name: 'animated-list-demo',
      type: 'components:example',
      files: ['example/animated-list-demo.tsx'],
   },
   {
      name: 'animated-lines-demo',
      type: 'components:example',
      files: ['example/animated-lines-demo.tsx'],
   },
   {
      name: 'animated-shiny-text-demo',
      type: 'components:example',
      files: ['example/animated-shiny-text-demo.tsx'],
   },
   {
      name: 'particles-demo',
      type: 'components:example',
      files: ['example/particles-demo.tsx'],
   },
   {
      name: 'animated-grid-pattern-demo',
      type: 'components:example',
      files: ['example/animated-grid-pattern-demo.tsx'],
   },
   {
      name: 'border-beam-demo',
      type: 'components:example',
      files: ['example/border-beam-demo.tsx'],
   },
   {
      name: 'animated-beam-demo',
      type: 'components:example',
      files: ['example/animated-beam-demo.tsx'],
   },
   {
      name: 'animated-beam-unidirectional',
      type: 'components:example',
      files: ['example/animated-beam-unidirectional.tsx'],
   },
   {
      name: 'animated-beam-bidirectional',
      type: 'components:example',
      files: ['example/animated-beam-bidirectional.tsx'],
   },
   {
      name: 'animated-beam-multiple-inputs',
      type: 'components:example',
      files: ['example/animated-beam-multiple-inputs.tsx'],
   },
   {
      name: 'animated-beam-multiple-outputs',
      type: 'components:example',
      files: ['example/animated-beam-multiple-outputs.tsx'],
   },
   {
      name: 'animated-feature-card-1',
      type: 'components:example',
      files: ['example/animated-feature-card-1.tsx'],
   },
   {
      name: 'animated-feature-card-2',
      type: 'components:example',
      files: ['example/animated-feature-card-2.tsx'],
   },
   {
      name: 'animated-feature-card-3',
      type: 'components:example',
      files: ['example/animated-feature-card-3.tsx'],
   },
   {
      name: 'animated-feature-card-4',
      type: 'components:example',
      files: ['example/animated-feature-card-4.tsx'],
   },
   {
      name: 'animated-feature-card-5',
      type: 'components:example',
      files: ['example/animated-feature-card-5.tsx'],
   },
   {
      name: 'animated-feature-card-6',
      type: 'components:example',
      files: ['example/animated-feature-card-6.tsx'],
   },
   {
      name: 'animated-feature-card-7',
      type: 'components:example',
      files: ['example/animated-feature-card-7.tsx'],
   },
   {
      name: 'animated-feature-card-8',
      type: 'components:example',
      files: ['example/animated-feature-card-8.tsx'],
   },
   {
      name: 'animated-feature-card-9',
      type: 'components:example',
      files: ['example/animated-feature-card-9.tsx'],
   },
   {
      name: 'animated-feature-card-10',
      type: 'components:example',
      files: ['example/animated-feature-card-10.tsx'],
   },
   {
      name: 'text-reveal-demo',
      type: 'components:example',
      files: ['example/text-reveal-demo.tsx'],
   },
   {
      name: 'animated-gradient-text-demo',
      type: 'components:example',
      files: ['example/animated-gradient-text-demo.tsx'],
   },
   {
      name: 'orbiting-circles-demo',
      type: 'components:example',
      files: ['example/orbiting-circles-demo.tsx'],
   },
   {
      name: 'dock-demo',
      type: 'components:example',
      files: ['example/dock-demo.tsx'],
   },
   {
      name: 'dock-demo-2',
      type: 'components:example',
      files: ['example/dock-demo-2.tsx'],
   },
   {
      name: 'dock-demo-3',
      type: 'components:example',
      files: ['example/dock-demo-3.tsx'],
   },
   {
      name: 'word-rotate-demo',
      type: 'components:example',
      files: ['example/word-rotate-demo.tsx'],
   },
   {
      name: 'avatar-circles-demo',
      type: 'components:example',
      files: ['example/avatar-circles-demo.tsx'],
   },
   {
      name: 'word-pull-up-demo',
      type: 'components:example',
      files: ['example/word-pull-up-demo.tsx'],
   },
   {
      name: 'typing-animation-demo',
      type: 'components:example',
      files: ['example/typing-animation-demo.tsx'],
   },
   {
      name: 'wavy-text-demo',
      type: 'components:example',
      files: ['example/wavy-text-demo.tsx'],
   },
   {
      name: 'blur-in-demo',
      type: 'components:example',
      files: ['example/blur-in-demo.tsx'],
   },
   {
      name: 'separate-away-demo',
      type: 'components:example',
      files: ['example/separate-away-demo.tsx'],
   },
   {
      name: 'scroll-based-velocity-demo',
      type: 'components:example',
      files: ['example/scroll-based-velocity-demo.tsx'],
   },
   {
      name: 'letter-pullup-demo',
      type: 'components:example',
      files: ['example/letter-pullup-demo.tsx'],
   },
   {
      name: 'flip-text-demo',
      type: 'components:example',
      files: ['example/flip-text-demo.tsx'],
   },
   {
      name: 'sparkles-text-demo',
      type: 'components:example',
      files: ['example/sparkles-text-demo.tsx'],
   },
   {
      name: 'icon-cloud-demo',
      type: 'components:example',
      files: ['example/icon-cloud-demo.tsx'],
   },
   {
      name: 'wavy-dot-pattern-demo',
      type: 'components:example',
      files: ['example/wavy-dot-pattern-demo.tsx'],
   },
   {
      name: 'gradual-spacing-demo',
      type: 'components:example',
      files: ['example/gradual-spacing-demo.tsx'],
   },
   {
      name: 'word-fade-in-demo',
      type: 'components:example',
      files: ['example/word-fade-in-demo.tsx'],
   },
   {
      name: 'fade-text-demo',
      type: 'components:example',
      files: ['example/fade-text-demo.tsx'],
   },
   {
      name: 'shiny-button-demo',
      type: 'components:example',
      files: ['example/shiny-button-demo.tsx'],
   },
   {
      name: 'box-reveal-demo',
      type: 'components:example',
      files: ['example/box-reveal-demo.tsx'],
   },
   {
      name: 'gauge-circle-demo',
      type: 'components:example',
      files: ['example/gauge-circle-demo.tsx'],
   },
   {
      name: 'shine-border-demo',
      type: 'components:example',
      files: ['example/shine-border-demo.tsx'],
   },
   {
      name: 'shine-border-demo-2',
      type: 'components:example',
      files: ['example/shine-border-demo-2.tsx'],
   },
   {
      name: 'confetti-hover',
      type: 'components:example',
      files: ['example/confetti-hover.tsx'],
   },
   {
      name: 'confetti-basic-cannon',
      type: 'components:example',
      files: ['example/confetti-basic-cannon.tsx'],
   },
   {
      name: 'confetti-random-direction',
      type: 'components:example',
      files: ['example/confetti-random-direction.tsx'],
   },
   {
      name: 'confetti-fireworks',
      type: 'components:example',
      files: ['example/confetti-fireworks.tsx'],
   },
   {
      name: 'confetti-stars',
      type: 'components:example',
      files: ['example/confetti-stars.tsx'],
   },
   {
      name: 'confetti-side-cannons',
      type: 'components:example',
      files: ['example/confetti-side-cannons.tsx'],
   },
   {
      name: 'confetti-custom-shapes',
      type: 'components:example',
      files: ['example/confetti-custom-shapes.tsx'],
   },
   {
      name: 'confetti-emoji',
      type: 'components:example',
      files: ['example/confetti-emoji.tsx'],
   },
   {
      name: 'animated-subscribe-button-demo',
      type: 'components:example',
      files: ['example/animated-subscribe-button-demo.tsx'],
   },
   {
      name: 'cool-mode-demo',
      type: 'components:example',
      files: ['example/cool-mode-demo.tsx'],
   },
   {
      name: 'cool-mode-custom',
      type: 'components:example',
      files: ['example/cool-mode-custom.tsx'],
   },
   {
      name: 'timeline-demo',
      type: 'components:example',
      registryDependencies: ['timeline'],
      files: ['example/timeline-demo.tsx'],
   },
   {
      name: 'timeline-right',
      type: 'components:example',
      registryDependencies: ['timeline'],
      files: ['example/timeline-right.tsx'],
   },
   {
      name: 'timeline-alternate',
      type: 'components:example',
      registryDependencies: ['timeline'],
      files: ['example/timeline-alternate.tsx'],
   },
   {
      name: 'timeline-labels',
      type: 'components:example',
      registryDependencies: ['timeline'],
      files: ['example/timeline-labels.tsx'],
   },
   {
      name: 'star-rating-demo',
      type: 'components:example',
      files: ['example/star-rating-demo.tsx'],
   },
   {
      name: 'star-rating-colored',
      type: 'components:example',
      files: ['example/star-rating-colored.tsx'],
   },
   {
      name: 'star-rating-icon',
      type: 'components:example',
      files: ['example/star-rating-icon.tsx'],
   },
   {
      name: 'stepper-demo',
      type: 'components:example',
      registryDependencies: ['stepper'],
      files: ['example/stepper-demo.tsx'],
   },
   {
      name: 'stepper-custom-styles',
      type: 'components:example',
      registryDependencies: ['stepper'],
      files: ['example/stepper-custom-styles.tsx'],
   },
   {
      name: 'stepper-orientation',
      type: 'components:example',
      registryDependencies: ['stepper'],
      files: ['example/stepper-orientation.tsx'],
   },
   {
      name: 'stepper-description',
      type: 'components:example',
      registryDependencies: ['stepper'],
      files: ['example/stepper-description.tsx'],
   },
   {
      name: 'stepper-sizes',
      type: 'components:example',
      registryDependencies: ['stepper'],
      files: ['example/stepper-sizes.tsx'],
   },
   {
      name: 'stepper-form',
      type: 'components:example',
      registryDependencies: ['stepper'],
      files: ['example/stepper-form.tsx'],
   },
   {
      name: 'stepper-variants',
      type: 'components:example',
      registryDependencies: ['stepper'],
      files: ['example/stepper-variants.tsx'],
   },
   {
      name: 'stepper-custom-icons',
      type: 'components:example',
      registryDependencies: ['stepper'],
      files: ['example/stepper-custom-icons.tsx'],
   },
   {
      name: 'stepper-footer-inside',
      type: 'components:example',
      registryDependencies: ['stepper'],
      files: ['example/stepper-footer-inside.tsx'],
   },
   {
      name: 'stepper-scroll-tracking',
      type: 'components:example',
      registryDependencies: ['stepper'],
      files: ['example/stepper-scroll-tracking.tsx'],
   },
   {
      name: 'stepper-clickable-steps',
      type: 'components:example',
      registryDependencies: ['stepper'],
      files: ['example/stepper-clickable-steps.tsx'],
   },
   {
      name: 'stepper-optional-steps',
      type: 'components:example',
      registryDependencies: ['stepper'],
      files: ['example/stepper-optional-steps.tsx'],
   },
   {
      name: 'stepper-state',
      type: 'components:example',
      registryDependencies: ['stepper'],
      files: ['example/stepper-state.tsx'],
   },
   {
      name: 'tour-demo',
      type: 'components:example',
      files: ['example/tour-demo.tsx'],
   },
   {
      name: 'toc-demo',
      type: 'components:example',
      files: ['example/toc-demo.tsx'],
   },
   {
      name: 'toc-nested',
      type: 'components:example',
      files: ['example/toc-nested.tsx'],
   },
   {
      name: 'toc-active',
      type: 'components:example',
      files: ['example/toc-active.tsx'],
   },
   {
      name: 'multi-select-basic',
      type: 'components:example',
      registryDependencies: ['multi-select'],
      files: ['example/multi-select-basic.tsx'],
   },
   {
      name: 'multi-select-filter',
      type: 'components:example',
      registryDependencies: ['multi-select'],
      files: ['example/multi-select-filter.tsx'],
   },
   {
      name: 'multi-select-controllable-search',
      type: 'components:example',
      registryDependencies: ['multi-select'],
      files: ['example/multi-select-controllable-search.tsx'],
   },
   {
      name: 'multi-select-input-custom',
      type: 'components:example',
      registryDependencies: ['multi-select'],
      files: ['example/multi-select-input-custom.tsx'],
   },
   {
      name: 'multi-select-limit-count',
      type: 'components:example',
      registryDependencies: ['multi-select'],
      files: ['example/multi-select-limit-count.tsx'],
   },
   {
      name: 'multi-select-limit-display-length',
      type: 'components:example',
      registryDependencies: ['multi-select'],
      files: ['example/multi-select-limit-display-length.tsx'],
   },
   {
      name: 'multi-select-form',
      type: 'components:example',
      registryDependencies: ['multi-select'],
      files: ['example/multi-select-form.tsx'],
   },
   {
      name: 'scroll-progress-demo',
      type: 'components:example',
      files: ['example/scroll-progress-demo.tsx'],
   },
   {
      name: 'video-modal-demo',
      type: 'components:example',
      files: ['example/video-modal-demo.tsx'],
   },
   {
      name: 'scratch-to-reveal-demo',
      type: 'components:example',
      files: ['example/scratch-to-reveal-demo.tsx'],
   },
   {
      name: 'confetti-demo',
      type: 'components:example',
      files: ['example/confetti-demo.tsx'],
   },
   {
      name: 'blur-fade-demo',
      type: 'components:example',
      files: ['example/blur-fade-demo.tsx'],
   },
   {
      name: 'blur-fade-text-demo',
      type: 'components:example',
      files: ['example/blur-fade-text-demo.tsx'],
   },
   {
      name: 'file-tree-demo',
      type: 'components:example',
      files: ['example/file-tree-demo.tsx'],
   },
   {
      name: 'rainbow-button-demo',
      type: 'components:example',
      files: ['example/rainbow-button-demo.tsx'],
   },
   {
      name: 'hero-video-dialog-demo',
      type: 'components:example',
      files: ['example/hero-video-dialog-demo.tsx'],
   },
   {
      name: 'hero-video-dialog-demo-top-in-bottom-out',
      type: 'components:example',
      files: ['example/hero-video-dialog-demo-top-in-bottom-out.tsx'],
   },
   {
      name: 'flickering-grid-demo',
      type: 'components:example',
      files: ['example/flickering-grid-demo.tsx'],
   },
   {
      name: 'flickering-grid-rounded-demo',
      type: 'components:example',
      files: ['example/flickering-grid-rounded-demo.tsx'],
   },
   {
      name: 'hyper-text-demo',
      type: 'components:example',
      files: ['example/hyper-text-demo.tsx'],
   },
   {
      name: 'safari-demo',
      type: 'components:example',
      files: ['example/safari-demo.tsx'],
   },
   {
      name: 'safari-demo-2',
      type: 'components:example',
      files: ['example/safari-demo-2.tsx'],
   },
   {
      name: 'iphone-15-pro-demo',
      type: 'components:example',
      files: ['example/iphone-15-pro-demo.tsx'],
   },
   {
      name: 'iphone-15-pro-demo-2',
      type: 'components:example',
      files: ['example/iphone-15-pro-demo-2.tsx'],
   },
]
