import type { Registry } from '~/registry/schema'

export const ui: Registry = [
   {
      name: 'accordion',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-accordion'],
      files: ['ui/accordion.tsx'],
   },
   {
      name: 'alert',
      type: 'components:ui',
      files: ['ui/alert.tsx'],
   },
   {
      name: 'alert-dialog',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-alert-dialog'],
      registryDependencies: ['button'],
      files: ['ui/alert-dialog.tsx'],
   },
   {
      name: 'animated-beam',
      type: 'components:ui',
      files: ['ui/animated-beam.tsx'],
   },
   {
      name: 'animated-grid-pattern',
      type: 'components:ui',
      files: ['ui/animated-grid-pattern.tsx'],
   },
   {
      name: 'animated-lines',
      type: 'components:ui',
      files: ['ui/animated-lines.tsx'],
   },
   {
      name: 'animated-list',
      type: 'components:ui',
      files: ['ui/animated-list.tsx'],
   },
   {
      name: 'animated-shiny-text',
      type: 'components:ui',
      files: ['ui/animated-shiny-text.tsx'],
   },
   {
      name: 'animated-subscribe-button',
      type: 'components:ui',
      files: ['ui/animated-subscribe-button.tsx'],
   },
   {
      name: 'animated-gradient-text',
      type: 'components:ui',
      files: ['ui/animated-gradient-text.tsx'],
   },
   {
      name: 'aspect-ratio',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-aspect-ratio'],
      files: ['ui/aspect-ratio.tsx'],
   },
   {
      name: 'avatar',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-avatar'],
      files: ['ui/avatar.tsx'],
   },
   {
      name: 'avatar-circles',
      type: 'components:ui',
      files: ['ui/avatar-circles.tsx'],
   },
   {
      name: 'badge',
      type: 'components:ui',
      files: ['ui/badge.tsx'],
   },
   {
      name: 'bento-grid',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-icons'],
      registryDependencies: ['button'],
      files: ['ui/bento-grid.tsx'],
   },
   {
      name: 'blur-in',
      type: 'components:ui',
      files: ['ui/blur-in.tsx'],
   },
   {
      name: 'border-beam',
      type: 'components:ui',
      files: ['ui/border-beam.tsx'],
   },
   {
      name: 'box-reveal',
      type: 'components:ui',
      files: ['ui/box-reveal.tsx'],
   },
   {
      name: 'breadcrumb',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-slot'],
      files: ['ui/breadcrumb.tsx'],
   },
   {
      name: 'button',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-slot'],
      files: ['ui/button.tsx'],
   },
   {
      name: 'blur-fade',
      type: 'components:ui',
      files: ['ui/blur-fade.tsx'],
   },
   {
      name: 'calendar',
      type: 'components:ui',
      dependencies: ['react-day-picker', 'date-fns'],
      registryDependencies: ['button'],
      files: ['ui/calendar.tsx'],
   },
   {
      name: 'card',
      type: 'components:ui',
      files: ['ui/card.tsx'],
   },
   {
      name: 'carousel',
      type: 'components:ui',
      files: ['ui/carousel.tsx'],
      registryDependencies: ['button'],
      dependencies: ['embla-carousel-react'],
   },
   {
      name: 'chart',
      type: 'components:ui',
      files: ['ui/chart.tsx'],
      dependencies: ['recharts'],
   },
   {
      name: 'checkbox',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-checkbox'],
      files: ['ui/checkbox.tsx'],
   },
   {
      name: 'client-tweet-card',
      type: 'components:ui',
      files: ['ui/client-tweet-card.tsx'],
   },
   {
      name: 'collapsible',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-collapsible'],
      files: ['ui/collapsible.tsx'],
   },
   {
      name: 'command',
      type: 'components:ui',
      dependencies: ['cmdk'],
      registryDependencies: ['dialog'],
      files: ['ui/command.tsx'],
   },
   {
      name: 'confetti',
      type: 'components:ui',
      dependencies: ['canvas-confetti'],
      files: ['ui/confetti.tsx'],
   },
   {
      name: 'context-menu',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-context-menu'],
      files: ['ui/context-menu.tsx'],
   },
   {
      name: 'cool-mode',
      type: 'components:ui',
      files: ['ui/cool-mode.tsx'],
   },
   {
      name: 'dialog',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-dialog'],
      files: ['ui/dialog.tsx'],
   },
   {
      name: 'dock',
      type: 'components:ui',
      files: ['ui/dock.tsx'],
   },
   {
      name: 'dot-pattern',
      type: 'components:ui',
      files: ['ui/dot-pattern.tsx'],
   },
   {
      name: 'drawer',
      type: 'components:ui',
      dependencies: ['vaul', '@radix-ui/react-dialog'],
      files: ['ui/drawer.tsx'],
   },
   {
      name: 'dropdown-menu',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-dropdown-menu'],
      files: ['ui/dropdown-menu.tsx'],
   },
   {
      name: 'fade-text',
      type: 'components:ui',
      files: ['ui/fade-text.tsx'],
   },
   {
      name: 'file-tree',
      type: 'components:ui',
      files: ['ui/file-tree.tsx'],
   },
   {
      name: 'flip-text',
      type: 'components:ui',
      files: ['ui/flip-text.tsx'],
   },
   {
      name: 'form',
      type: 'components:ui',
      dependencies: [
         '@radix-ui/react-label',
         '@radix-ui/react-slot',
         '@hookform/resolvers',
         'zod',
         'react-hook-form',
      ],
      registryDependencies: ['button', 'label'],
      files: ['ui/form.tsx'],
   },
   {
      name: 'globe',
      type: 'components:ui',
      dependencies: ['react-spring'],
      files: ['ui/globe.tsx'],
   },
   {
      name: 'gradual-spacing',
      type: 'components:ui',
      files: ['ui/gradual-spacing.tsx'],
   },
   {
      name: 'grid-pattern',
      type: 'components:ui',
      files: ['ui/grid-pattern.tsx'],
   },
   {
      name: 'gauge-circle',
      type: 'components:ui',
      files: ['ui/gauge-circle.tsx'],
   },
   {
      name: 'hero-video',
      type: 'components:ui',
      files: ['ui/hero-video.tsx'],
   },
   {
      name: 'hover-card',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-hover-card'],
      files: ['ui/hover-card.tsx'],
   },
   {
      name: 'icon-cloud',
      type: 'components:ui',
      dependencies: ['react-icon-cloud'],
      files: ['ui/icon-cloud.tsx'],
   },
   {
      name: 'input',
      type: 'components:ui',
      files: ['ui/input.tsx'],
   },
   {
      name: 'input-otp',
      type: 'components:ui',
      dependencies: ['input-otp'],
      files: ['ui/input-otp.tsx'],
   },
   {
      name: 'input-phone',
      type: 'components:ui',
      dependencies: ['react-phone-number-input'],
      registryDependencies: ['button', 'input', 'popover'],
      files: ['ui/input-phone.tsx'],
   },
   {
      name: 'label',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-label'],
      files: ['ui/label.tsx'],
   },
   {
      name: 'letter-pullup',
      type: 'components:ui',
      files: ['ui/letter-pullup.tsx'],
   },
   {
      name: 'linear-gradient',
      type: 'components:ui',
      files: ['ui/linear-gradient.tsx'],
   },
   {
      name: 'magic-card',
      type: 'components:ui',
      files: ['ui/magic-card.tsx'],
   },
   {
      name: 'marquee',
      type: 'components:ui',
      files: ['ui/marquee.tsx'],
   },
   {
      name: 'menubar',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-menubar'],
      files: ['ui/menubar.tsx'],
   },
   {
      name: 'meteors',
      type: 'components:ui',
      files: ['ui/meteors.tsx'],
   },
   {
      name: 'multi-select',
      type: 'components:ui',
      files: ['ui/multi-select.tsx'],
   },
   {
      name: 'navigation-menu',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-navigation-menu'],
      files: ['ui/navigation-menu.tsx'],
   },
   {
      name: 'neon-gradient-card',
      type: 'components:ui',
      files: ['ui/neon-gradient-card.tsx'],
   },
   {
      name: 'number-ticker',
      type: 'components:ui',
      files: ['ui/number-ticker.tsx'],
   },
   {
      name: 'orbiting-circles',
      type: 'components:ui',
      files: ['ui/orbiting-circles.tsx'],
   },
   {
      name: 'pagination',
      type: 'components:ui',
      registryDependencies: ['button'],
      files: ['ui/pagination.tsx'],
   },
   {
      name: 'particles',
      type: 'components:ui',
      files: ['ui/particles.tsx'],
   },
   {
      name: 'popover',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-popover'],
      files: ['ui/popover.tsx'],
   },
   {
      name: 'progress',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-progress'],
      files: ['ui/progress.tsx'],
   },
   {
      name: 'pulsating-button',
      type: 'components:ui',
      files: ['ui/pulsating-button.tsx'],
   },
   {
      name: 'radio-group',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-radio-group'],
      files: ['ui/radio-group.tsx'],
   },
   {
      name: 'radial-gradient',
      type: 'components:ui',
      files: ['ui/radial-gradient.tsx'],
   },
   {
      name: 'resizable',
      type: 'components:ui',
      dependencies: ['react-resizable-panels'],
      files: ['ui/resizable.tsx'],
   },
   {
      name: 'retro-grid',
      type: 'components:ui',
      files: ['ui/retro-grid.tsx'],
   },
   {
      name: 'ripple',
      type: 'components:ui',
      files: ['ui/ripple.tsx'],
   },
   {
      name: 'scroll-area',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-scroll-area'],
      files: ['ui/scroll-area.tsx'],
   },
   {
      name: 'scroll-based-velocity',
      dependencies: ['@motionone/utils'],
      type: 'components:ui',
      files: ['ui/scroll-based-velocity.tsx'],
   },
   {
      name: 'scroll-progress',
      type: 'components:ui',
      files: ['ui/scroll-progress.tsx'],
   },
   {
      name: 'select',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-select'],
      files: ['ui/select.tsx'],
   },
   {
      name: 'separate-away',
      type: 'components:ui',
      files: ['ui/separate-away.tsx'],
   },
   {
      name: 'separator',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-separator'],
      files: ['ui/separator.tsx'],
   },
   {
      name: 'sheet',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-dialog'],
      files: ['ui/sheet.tsx'],
   },
   {
      name: 'shimmer-button',
      type: 'components:ui',
      files: ['ui/shimmer-button.tsx'],
   },
   {
      name: 'shine-border',
      type: 'components:ui',
      files: ['ui/shine-border.tsx'],
   },
   {
      name: 'shiny-button',
      type: 'components:ui',
      files: ['ui/shiny-button.tsx'],
   },
   {
      name: 'skeleton',
      type: 'components:ui',
      files: ['ui/skeleton.tsx'],
   },
   {
      name: 'slider',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-slider'],
      files: ['ui/slider.tsx'],
   },
   {
      name: 'sonner',
      type: 'components:ui',
      dependencies: ['sonner', 'next-themes'],
      files: ['ui/sonner.tsx'],
   },
   {
      name: 'sparkles-text',
      type: 'components:ui',
      files: ['ui/sparkles-text.tsx'],
   },
   {
      name: 'star-rating',
      type: 'components:ui',
      files: ['ui/star-rating.tsx'],
   },
   {
      name: 'switch',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-switch'],
      files: ['ui/switch.tsx'],
   },
   {
      name: 'stepper',
      type: 'components:ui',
      files: ['ui/stepper.tsx'],
   },
   {
      name: 'scratch-to-reveal',
      type: 'components:ui',
      files: ['ui/scratch-to-reveal.tsx'],
   },
   {
      name: 'table',
      type: 'components:ui',
      files: ['ui/table.tsx'],
   },
   {
      name: 'tabs',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-tabs'],
      files: ['ui/tabs.tsx'],
   },
   {
      name: 'textarea',
      type: 'components:ui',
      files: ['ui/textarea.tsx'],
   },
   {
      name: 'text-reveal',
      type: 'components:ui',
      files: ['ui/text-reveal.tsx'],
   },
   {
      name: 'timeline',
      type: 'components:ui',
      files: ['ui/timeline.tsx'],
   },
   {
      name: 'toc',
      type: 'components:ui',
      files: ['ui/toc.tsx'],
   },
   {
      name: 'toast',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-toast'],
      files: ['ui/toast.tsx', 'ui/use-toast.ts', 'ui/toaster.tsx'],
   },
   {
      name: 'toggle',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-toggle'],
      files: ['ui/toggle.tsx'],
   },
   {
      name: 'toggle-group',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-toggle-group'],
      registryDependencies: ['toggle'],
      files: ['ui/toggle-group.tsx'],
   },
   {
      name: 'tooltip',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-tooltip'],
      files: ['ui/tooltip.tsx'],
   },
   {
      name: 'tour',
      type: 'components:ui',
      files: ['ui/tour.tsx'],
   },
   {
      name: 'typing-animation',
      type: 'components:ui',
      files: ['ui/typing-animation.tsx'],
   },
   {
      name: 'tweet-card',
      type: 'components:ui',
      files: ['ui/tweet-card.tsx'],
   },
   {
      name: 'video-modal',
      type: 'components:ui',
      dependencies: ['@radix-ui/react-dialog'],
      files: ['ui/video-modal.tsx'],
   },
   {
      name: 'wavy-dot-pattern',
      type: 'components:ui',
      dependencies: ['react-anime'],
      files: ['ui/wavy-dot-pattern.tsx'],
   },
   {
      name: 'wavy-text',
      type: 'components:ui',
      files: ['ui/wavy-text.tsx'],
   },
   {
      name: 'word-fade-in',
      type: 'components:ui',
      files: ['ui/word-fade-in.tsx'],
   },
   {
      name: 'word-pull-up',
      type: 'components:ui',
      files: ['ui/word-pull-up.tsx'],
   },
   {
      name: 'word-rotate',
      type: 'components:ui',
      files: ['ui/word-rotate.tsx'],
   },
   {
      name: 'rainbow-button',
      type: 'components:ui',
      files: ['ui/rainbow-button.tsx'],
   },
]
